In [26]:
%load_ext autoreload
%autoreload 2

import pandas as pd
pd.set_option('display.max_rows', None)

pd.set_option('display.max_columns', None)

raw = pd.read_csv('../actions_taken_1-2-3_loan_purposes_1_state_PA.csv', low_memory=False)

copy = raw.copy()

In [27]:

from cleaner import constant_val

display(constant_val(copy))

from modules.cleaner import constant_val

display(constant_val(copy))

                                      column  unique values
0                              activity_year              1
1                                        lei            934
2                             derived_msa-md             18
3                                 state_code              1
4                                county_code             67
5                               census_tract           3376
6                      conforming_loan_limit              3
7                  derived_loan_product_type              7
8                  derived_dwelling_category              4
9                          derived_ethnicity              5
10                              derived_race              9
11                               derived_sex              4
12                              action_taken              3
13                            purchaser_type             11
14                               preapproval              2
15                                 loan_type              4
16                              loan_purpose              1
17                               lien_status              2
18                          reverse_mortgage              3
19                   open-end_line_of_credit              3
20            business_or_commercial_purpose              3
21                               loan_amount            352
22                       loan_to_value_ratio          23919
23                             interest_rate           1934
24                               rate_spread          11043
25                              hoepa_status              3
26                          total_loan_costs          91078
27                     total_points_and_fees            759
28                       origination_charges          51749
29                           discount_points          39920
30                            lender_credits          18871
31                                 loan_term            240
32                   prepayment_penalty_term             10
33                         intro_rate_period             66
34                     negative_amortization              3
35                     interest_only_payment              3
36                           balloon_payment              3
37              other_nonamortizing_features              3
38                            property_value            427
39                       construction_method              2
40                            occupancy_type              3
41   manufactured_home_secured_property_type              4
42  manufactured_home_land_property_interest              6
43                               total_units              9
44              multifamily_affordable_units             15
45                                    income           1284
46                      debt_to_income_ratio             20
47               applicant_credit_score_type             15
48            co-applicant_credit_score_type             16
49                     applicant_ethnicity-1              8
50                     applicant_ethnicity-2              6
51                     applicant_ethnicity-3              5
52                     applicant_ethnicity-4              1
53                     applicant_ethnicity-5              1
54                  co-applicant_ethnicity-1              9
55                  co-applicant_ethnicity-2              6
56                  co-applicant_ethnicity-3              3
57                  co-applicant_ethnicity-4              1
58                  co-applicant_ethnicity-5              1
59              applicant_ethnicity_observed              3
60           co-applicant_ethnicity_observed              4
61                          applicant_race-1             17
62                          applicant_race-2             16
63                          applicant_race-3             14
64                          applicant_race-4             12
65                          applicant_race-5              7
66                       co-applicant_race-1             18
67                       co-applicant_race-2             15
68                       co-applicant_race-3             13
69                       co-applicant_race-4              9
70                       co-applicant_race-5              5
71                   applicant_race_observed              3
72                co-applicant_race_observed              4
73                             applicant_sex              5
74                          co-applicant_sex              6
75                    applicant_sex_observed              3
76                 co-applicant_sex_observed              4
77                             applicant_age              8
78                          co-applicant_age              9
79                    applicant_age_above_62              2
80                 co-applicant_age_above_62              2
81                 submission_of_application              3
82          initially_payable_to_institution              4
83                                     aus-1              8
84                                     aus-2              6
85                                     aus-3              6
86                                     aus-4              3
87                                     aus-5              3
88                           denial_reason-1             11
89                           denial_reason-2              9
90                           denial_reason-3              9
91                           denial_reason-4              9
92                          tract_population           2496
93         tract_minority_population_percent           2377
94         ffiec_msa_md_median_family_income             19
95            tract_to_msa_income_percentage            241
96                tract_owner_occupied_units           1610
97            tract_one_to_four_family_homes           1752
98         tract_median_age_of_housing_units             69

        0
0       1
1     934
2      18
3       1
4      67
5    3376
6       3
7       7
8       4
9       5
10      9
11      4
12      3
13     11
14      2
15      4
16      1
17      2
18      3
19      3
20      3
21    352
22  23919
23   1934
24  11043
25      3
26  91078
27    759
28  51749
29  39920
30  18871
31    240
32     10
33     66
34      3
35      3
36      3
37      3
38    427
39      2
40      3
41      4
42      6
43      9
44     15
45   1284
46     20
47     15
48     16
49      8
50      6
51      5
52      1
53      1
54      9
55      6
56      3
57      1
58      1
59      3
60      4
61     17
62     16
63     14
64     12
65      7
66     18
67     15
68     13
69      9
70      5
71      3
72      4
73      5
74      6
75      3
76      4
77      8
78      9
79      2
80      2
81      3
82      4
83      8
84      6
85      6
86      3
87      3
88     11
89      9
90      9
91      9
92   2496
93   2377
94     19
95    241
96   1610
97   1752
98     69